import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/modules/common/header/Header";
import { WagmiProviders } from "@/modules/wagmi/components/WagmiProvider/WagmiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecosystem wallet demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Memo: Adding ThirdwebProvider makes the app slow in reflecting the changes */}
        <WagmiProviders>
          <Header />
          <div>{children}</div>
        </WagmiProviders>
      </body>
    </html>
  );
}
